### ISSUE TITLE
VICE settings?

### ISSUE THREAD

**Issue by ktamas77** [retrocomputacion/retroterm#1]
Amazing project, exactly what I'm looking for!
Could you please help to describe how exactly VICE needs to be configured in order to make this work?

**Comment by retrocomputacion** [comment]
Hi, thanks!

For VICE you'll ideally use TCPser for emulated modem, is possible to use direct connection, but your mileage might vary due to the way VICE initializes TCP connections. 
For VICE (you need 3.6.1 or newer), in the settings window, go to "Peripheral devices->RS232" and check "Enable userport RS232 emulation".
For "RS-232 Interface type" select "RS232, normal control lines levels
For Device select for example Serial 3 and in Baud select 57600

In RS232 Devices, Serial 3 type in the IP and port to your TCPser instance and make sure you check the IP232 box for serial 3

And that's it settings wise, you first execute TCPser then start VICE. After running Retroterm you should be able to type AT commands to TCPser. If Retroterm doesnt respond to the keyboard then VICE has failed to connect to TCPser and you should quit both VICE and TCPser and run them again. 

Here's a list of Turbo56K BBSs currently online:

Thierry's Lair
           THIERRYSLAIR.DYNET.COM:64128

LU8FJH BBS
               LU8FJH-C64.DDNS.NET:6402

LU4FBU BBS
                   LU4FBU.DDNS.NET:6400

**Comment by Paulie420** [comment]
Thanks for posting these details. I'm running tcpser with:
tcpser -v 25232 -s 57600 -l 4

and have setup VICE preferences like you say, but lu8fjh bbs still tells me I need a terminal program w/ turbo56k support. I'm on the retroterm 0.14 version... wonder what step I missed, or is my tcpser settings wrong? also, the IP I entered into VICE is 'localhost:25232' - maybe it NEEDS the IP??? Hmmmm.... thank you!!

**Comment by Paulie420** [comment]
Just a tip, you can bypass the entire tcpser thing by just typing the bbs address IN the Serial # line in VICE settings/RS232... select 57600 and the Serial # when retroterm is running and boom - you connect.

**Comment by retrocomputacion** [comment]
> Just a tip, you can bypass the entire tcpser thing by just typing the bbs address IN the Serial # line in VICE settings/RS232... select 57600 and the Serial # when retroterm is running and boom - you connect.

If youre not using TCPSer, then dont check the IP232 box in the options. That's only needed when connecting thru TCPSer

**Comment by ktamas77** [comment]
thanks everyone.
